name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:      # Allows manual start

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Arjit74
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate Contribution Snake Animation"
          add: "dist/github-contribution-grid-snake.svg"
